#!/bin/bash
if [ $# -lt 1 ] ; then
 echo "Usage: cscope_builder <path_to_project>"
 exit 1
fi
project=$1
cd $project

rm cscope*
rm tags

if [ $# -gt 1 ] && [ $2 == "clean" ]; then
	echo "Removed cscope and tag files."
	echo ""
	exit 1
fi
find . -name '*.c' >cscope.files
find . -name '*.cpp' >>cscope.files
find . -name '*.h' >>cscope.files
find . -name '*.javac' >>cscope.files
ctags -L cscope.files
cscope -Rbkq
echo "Done building database. Run cscope -d."
echo ""
